<h1><?php echo MODULE_TITLE; ?></h1>
<dl>
<dt><font style="font-size: 18px">Как долго ждать изготовления заказанной мебели?</font></dt>
	<dd><span style="padding: 50px">Существует складская программа. В зависимости от объема заказа, не более двух недель от даты поступления оплаты.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">Возможна ли доставка и сборка мебели на месте?</font></dt>
	<dd><span style="padding: 50px">В стоимость мебели  данные услуги не включены, но можем произвести доставку и сборку за отдельную плату.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">Какие цвета мебели входят в складскую программу?</font></dt>
	<dd><span style="padding: 50px">Основной цвет мебели  для офиса – вишня оксфорд, мебель других цветов изготавливается под заказ.
	</span>
	</dd>
		
<dt><font style="font-size: 18px">Можно ли доукомплектовать кабинет нестандартной мебелью?</font></dt>
	<dd><span style="padding: 50px">Да, в течение двух недель с заказчиком будут утверждены эскизы, стоимость  и изготовлена мебель по индивидуальным проектам.
	</span>
	</dd>

<dt><font style="font-size: 18px">Осуществляете ли вы доставку мебели в другие регионы?</font>
</dt>
	<dd><span style="padding: 50px">Да, мы сотрудничаем со многими транспортными компаниями.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">Какой покупатель считается оптовым?</font>
</dt>
	<dd><span style="padding: 50px">Покупатель приобретает мебель по оптовым ценам в двух случаях:<br/></span>
<span style="padding: 50px">	1. При разовой покупке, приобретая товар в кол-ве не менее 20 единиц на сумму не менее 50 000 руб.<br/></span>
<span style="padding: 50px">	2. При долгосрочном сотрудничестве на договорной основе.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">Существуют ли скидки при долгосрочном сотрудничестве?</font>
</dt>
	<dd><span style="padding: 50px">Да, приобретая мебель на определенную сумму, покупатель получает скидку в следующем месяце в размере:<br/></span>
<span style="padding: 50px">	100 000 руб.- 10%;<br/></span>
<span style="padding: 50px">	200 000 руб. –15%;<br/></span>
<span style="padding: 50px">	свыше 500 000 руб. – 20%.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">В каких цветах выполняется мебель для дома (комоды, тумбы)?</font>
	</dt>
	<dd><span style="padding: 50px">Цветовая гамма мебели для дома обширна, необходимо просто проконсультироваться с менеджером по наличию того или иного цвета.
	</span>
	</dd>
	
<dt><font style="font-size: 18px">Что делать, если не подходит размер, но устраивает модель?
	</dt>
	<dd><span style="padding: 50px">В индивидуальном порядке производится изменение размеров за небольшую доплату.
	</span>
	</dd>
	</dl>



<h1>Задать вопрос</h1>
<form name="buy" method="post" action="<?=PAGE_URL;?>" class="mainform">
	<div class="input-field">
		<label>Ваше имя</label>
		<input name="name" type="text" maxlength="255" value=""/>
	</div>
	<div class="input-field">
		<label>Как с Вами связаться</label>
		<input name="contacts" type="text" maxlength="255"  value=""/>
	</div>
	<div class="input-field">
		<label>Ваш вопрос</label>
		<textarea name="text" rows="10" cols="17"></textarea>
	</div>
	<button type="submit" class="submit">Отправить</button>
</form>